version: "2"
run:
  modules-download-mode: readonly
  tests: true
linters:
  enable:
    - gocritic
    - gocyclo
    - gosec
    - misspell
    - revive
    - unconvert
  settings:
    errcheck:
      check-type-assertions: false
      check-blank: false
    gocritic:
      enabled-tags:
        - diagnostic
      disabled-checks:
        - ifElseChain
        - singleCaseSwitch
    gocyclo:
      min-complexity: 40
    gosec:
      excludes:
        - G104
        - G304
      confidence: medium
    revive:
      severity: warning
      rules:
        - name: exported
          severity: warning
          disabled: true
        - name: error-return
        - name: error-naming
        - name: if-return
        - name: var-naming
        - name: indent-error-flow
          disabled: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
